# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a89f5856155290b8aa11727b1cfd7d11a19af6c80959425e9804bd7114c056bf438ef0e16b4e86409e425f82a46cd9786065fd4f6685dd9a33bcd157acf2da30

test:
  secret_key_base: f587b669355a0ad99039e0610394b3f3bc77146ecf342f12f7c37f0eaab86d797c1a2872037b2a33980bf4a93ed60e1af7d4d2b6cdfcd11c62eb4e6cc67d5dad

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
